// Programski ulazi. Fotografije prikazuju vrstu materijala, ne dokaz zaliha ili opreme firme.
// Širi program vodi na postojeći pregled ili upit dok konkretne artikle firma ne potvrdi.
export const OFFERINGS = [
  {
    id: 'suha-gradnja', name: 'Suha gradnja',
    keywords: ['Ploče', 'Profili', 'Pribor'],
    description: 'Ploče, profili i pribor za pregradne zidove, plafone i oblaganje.',
    image: '/editorial/programs/suha-gradnja.webp',
    detail: '/editorial/programs/suha-gradnja-detail.webp',
    alt: 'Složene gipsane ploče u skladištu — program suhe gradnje',
    href: '/prodavnica?kategorija=suha-gradnja#artikli', cta: 'Pogledajte suhu gradnju', mode: 'Katalog',
  },
  {
    id: 'izolacija', name: 'Izolacija',
    keywords: ['Toplota', 'Zvuk', 'Namjena'],
    description: 'Materijali za toplotnu i zvučnu izolaciju, prema mjestu ugradnje.',
    image: '/editorial/programs/izolacija.webp',
    detail: '/editorial/programs/izolacija-detail.webp',
    alt: 'Složene ploče kamene vune u otvorenom pakovanju — izolacija',
    href: '/prodavnica?kategorija=izolacija#artikli', cta: 'Pogledajte izolaciju', mode: 'Katalog',
  },
  {
    id: 'zidni-krovni', name: 'Zidni i krovni program',
    keywords: [],
    description: 'Pošaljite specifikaciju za provjeru programa i dostupnosti.',
    image: '/editorial/programs/zidni-krovni.webp',
    detail: '/editorial/programs/zidni-krovni-detail.webp',
    alt: 'Paleta glinenog crijepa — zidni i krovni program',
    href: '/upit-za-izvodjace?program=zidni-krovni', cta: 'Pošaljite specifikaciju', mode: 'Po upitu',
  },
  {
    id: 'veziva', name: 'Građevinska hemija i veziva',
    keywords: ['Ljepila', 'Mase', 'Veziva'],
    description: 'Ljepila, mase i veziva za pripremu, povezivanje i završnu obradu.',
    image: '/editorial/programs/veziva.webp',
    detail: '/editorial/programs/veziva-detail.webp',
    alt: 'Složene vreće cementa i veziva — građevinska hemija',
    href: '/prodavnica?kategorija=veziva#artikli', cta: 'Pogledajte hemiju i veziva', mode: 'Katalog',
  },
  {
    id: 'drvni-program', name: 'Drvni program',
    keywords: [],
    description: 'Pregled programa i upit za materijal, dimenzije i potrebne količine.',
    image: '/editorial/programs/drvni-program.webp',
    detail: '/editorial/programs/drvni-program-detail.webp',
    alt: 'Složena rezana građa — drvni program',
    href: '/prodavnica?kategorija=drvni-program#artikli', cta: 'Pogledajte drvni program', mode: 'Po upitu',
  },
  {
    id: 'sanitarna-oprema', name: 'Sanitarna oprema',
    keywords: [],
    description: 'Pregled sanitarnog programa i ponuda prema potrebama prostora.',
    image: '/editorial/programs/sanitarna-oprema.webp',
    detail: '/editorial/programs/sanitarna-oprema-detail.webp',
    alt: 'Bijela keramička WC šolja i bide u kupatilu — sanitarni program',
    href: '/prodavnica?kategorija=sanitarna-oprema#artikli', cta: 'Pogledajte sanitarni program', mode: 'Po upitu',
  },
] as const
